INSERT INTO products (product_key, price, stock, image_path, category)
VALUES
    ('avocado', 85.00, 100, '../assets/avocado.jpg', 'vegetables'),
    ('arugula', 40.00, 100, '../assets/arugula.jpg', 'vegetables'),
    ('tomatoes', 30.00, 100, '../assets/tomato.jpg', 'vegetables'),
    ('cucumber', 20.00, 100, '../assets/cucumber.jpg', 'vegetables'),
    ('potatoes', 15.00, 100, '../assets/potato.jpg', 'vegetables'),
    ('onion', 18.00, 100, '../assets/onion.jpg', 'vegetables'),
    ('carrot', 18.00, 100, '../assets/carrot.jpg', 'vegetables'),
    ('zucchini', 25.00, 100, '../assets/zucchini.jpg', 'vegetables'),
    ('pumpkin', 25.00, 100, '../assets/pumpkin.jpg', 'vegetables'),
    ('bell_pepper', 30.00, 100, '../assets/bellpepper.jpg', 'vegetables'),
    ('broccoli', 35.00, 100, '../assets/broccoli.jpg', 'vegetables'),
    ('capia_pepper', 40.00, 100, '../assets/capiapepper.jpg', 'vegetables'),
    ('pepper', 35.00, 100, '../assets/pepper.jpg', 'vegetables'),
    ('green_pepper', 25.00, 100, '../assets/greenpepper.jpg', 'vegetables'),
    ('sweet_pepper', 35.00, 100, '../assets/sweetpepper.jpg', 'vegetables'),
    ('cherry_tomato', 35.00, 100, '../assets/cherrytomato.jpg', 'vegetables'),
    ('celery', 25.00, 100, '../assets/celery.jpg', 'vegetables'),
    ('cauliflower', 35.00, 100, '../assets/cauliflower.jpg', 'vegetables'),
    ('iceberg_lettuce', 20.00, 100, '../assets/iceberglettuce.jpg', 'vegetables'),
    ('curly_lettuce', 25.00, 100, '../assets/curlyletuce.jpg', 'vegetables'),
    ('mushroom', 40.00, 100, '../assets/mushroom.jpg', 'vegetables'),
    ('garlic', 30.00, 100, '../assets/garlic.jpg', 'vegetables'),
    ('red_onion', 20.00, 100, '../assets/redonion.jpg', 'vegetables'),
    ('red_pepper', 35.00, 100, '../assets/redpepper.jpg', 'vegetables'),
    ('eggplant', 30.00, 100, '../assets/eggplant.jpg', 'vegetables'),
    ('fresh_mint', 20.00, 100, '../assets/freshmint.jpg', 'vegetables'),
    ('green_bean', 30.00, 100, '../assets/greenbean.jpg', 'vegetables'),
    ('kale', 35.00, 100, '../assets/kale.jpg', 'vegetables'),
    ('parsley', 15.00, 100, '../assets/parsley.jpg', 'vegetables'),
    ('radish', 20.00, 100, '../assets/radish.jpg', 'vegetables'),
    ('red_cabbage', 30.00, 100, '../assets/redcabbage.jpg', 'vegetables'),
    ('scallion', 15.00, 100, '../assets/scallion.jpg', 'vegetables'),
    ('olive_oil_1l', 255.95, 100, '../assets/oliveoil.jpg', 'olivesoils'),
    ('olive_oil_tin_5l', 799.95, 100, '../assets/oliveoilTin.png', 'olivesoils'),
    ('sunflower_oil_1l', 129.95, 100, '../assets/sunfloweroil.jpg', 'olivesoils'),
    ('butter_1kg', 575.95, 100, '../assets/butter.jpg', 'olivesoils'),
    ('milk_1l', 149.99, 100, '../assets/milk.jpg', 'dairy'),
    ('kefir_1l', 189.99, 100, '../assets/kefir.png', 'dairy'),
    ('cow_feta_cheese', 475.65, 100, '../assets/cowfetacheese.jpg', 'dairy'),
    ('twist_cheese', 350.55, 100, '../assets/twistcheese.jpg', 'dairy'),
    ('tulum_cheese', 420.95, 100, '../assets/tulumcheese.jpg', 'dairy'),
    ('goat_cheese', 590.00, 100, '../assets/goatcheese.jpg', 'dairy'),
    ('trakya_aged_cheese', 580.58, 100, '../assets/Trakyaagedcheese.jpg', 'dairy'),
    ('walnut_gouda_cheese', 2265.95, 100, '../assets/walnutgoudacheese.jpg', 'dairy'),
    ('gouda_cheese_truffle', 750.00, 100, '../assets/goudacheesewithtruffle.jpg', 'dairy'),
    ('gouda_cheese_pesto', 570.00, 100, '../assets/goudacheesewithredpesto.jpg', 'dairy'),
    ('delicious_cheese_balls', 650.00, 100, '../assets/deliciouscheeseballs.jpg', 'dairy'),
    ('sheep_yogurt', 229.75, 100, '../assets/sheepyogurtt.jpg', 'dairy'),
    ('water_buffalo_yogurt', 379.58, 100, '../assets/waterbuffaloyogurt.webp', 'dairy'),
    ('goat_yogurt', 330.00, 100, '../assets/goatyogurt.jpg', 'dairy'),
    ('cow_yogurt', 135.00, 100, '../assets/cowyogurt.jpg', 'dairy'),
    ('kars_gruyere_cheese', 600.00, 100, '../assets/KarsGruyereCheese.jpg', 'dairy'),
    ('string_cheese', 379.75, 100, '../assets/stringcheese.jpg', 'dairy'),
    ('plaited_cheese', 420.58, 100, '../assets/plaitedcheese.jpg', 'dairy'),
    ('mihali_cheese', 550.00, 100, '../assets/mihaliccheese.jpg', 'dairy'),
    ('kashar_cheese', 470.00, 100, '../assets/kasharcheese.jpg', 'dairy'),
    ('herby_cheese', 520.25, 100, '../assets/herbycheese.jpg', 'dairy'),
    ('orange', 55.00, 100, '../assets/orange.jpg', 'fruits'),
    ('banana', 60.00, 100, '../assets/banana.jpg', 'fruits'),
    ('grapes', 70.00, 100, '../assets/grapes.jpg', 'fruits'),
    ('green_apple', 50.00, 100, '../assets/greenapple.jpg', 'fruits'),
    ('red_apple', 50.00, 100, '../assets/redapple.jpg', 'fruits'),
    ('lemon', 35.00, 100, '../assets/lemon.jpg', 'fruits'),
    ('pear', 55.00, 100, '../assets/pear.jpg', 'fruits'),
    ('damson', 50.00, 100, '../assets/damson.jpg', 'fruits'),
    ('strawberry', 80.00, 100, '../assets/strawberry.jpg', 'fruits'),
    ('green_plum', 350.00, 100, '../assets/greenplum.jpg', 'fruits'),
    ('watermelon', 20.00, 100, '../assets/watermelon.jpg', 'fruits'),
    ('melon', 30.00, 100, '../assets/melon.jpg', 'fruits'),
    ('pineapple', 90.00, 100, '../assets/pineapple.jpg', 'fruits'),
    ('kiwi', 80.00, 100, '../assets/kiwi.jpg', 'fruits'),
    ('peach', 35.00, 100, '../assets/peach.jpeg', 'fruits'),
    ('cherry', 50.00, 100, '../assets/cherry.jpg', 'fruits'),
    ('pomegranate', 45.00, 100, '../assets/pomegranate.jpg', 'fruits'),
    ('purple_fig', 100.00, 100, '../assets/purplefig.jpg', 'fruits'),
    ('green_fig', 100.00, 100, '../assets/greenfig.jpeg', 'fruits'),
    ('quince', 40.00, 100, '../assets/quince.jpg', 'fruits'),
    ('dragon_fruit', 90.00, 100, '../assets/dragonFruit.jpg', 'fruits'),
    ('bread', 20.00, 100, '../assets/bread.jpg', 'bakedgoods'),
    ('daisy_bread', 30.00, 100, '../assets/daisybread.jpg', 'bakedgoods'),
    ('corn_bread', 35.00, 100, '../assets/cornbread.jpg', 'bakedgoods'),
    ('pitta_bread', 25.00, 100, '../assets/pittabread.jpg', 'bakedgoods'),
    ('sourdough_bread', 40.00, 100, '../assets/sourdoughbread.jpg', 'bakedgoods'),
    ('brown_bread', 30.00, 100, '../assets/brownbread.jpg', 'bakedgoods'),
    ('multigrain_bread', 32.00, 100, '../assets/multigrainbread.jpg', 'bakedgoods'),
    ('village_bread', 35.00, 100, '../assets/villagebread.jpg', 'bakedgoods'),
    ('whole_wheat_bread', 32.00, 100, '../assets/wholewheatbread.jpg', 'bakedgoods'),
    ('bagel', 20.00, 100, '../assets/bagel.jpg', 'bakedgoods'),
    ('gevrek', 22.00, 100, '../assets/gevrek.jpg', 'bakedgoods'),
    ('croissant', 25.00, 100, '../assets/croissant.jpg', 'bakedgoods'),
    ('pastry', 30.00, 100, '../assets/pastry.jpg', 'bakedgoods'),
    ('pastry_cheese', 35.00, 100, '../assets/pastrycheese.jpg', 'bakedgoods'),
    ('pastry_olive', 35.00, 100, '../assets/pastryolive.jpg', 'bakedgoods'),
    ('spring_rolls', 35.00, 100, '../assets/springrolls.jpg', 'bakedgoods'),
    ('cake', 50.00, 100, '../assets/cake.jpg', 'bakedgoods'),
    ('chocolate_cake', 60.00, 100, '../assets/chocolatecake.jpg', 'bakedgoods'),
    ('blackberry_jam', 84.30, 100, '../assets/blackberryjam.webp', 'sauces'),
    ('cherry_jam', 78.80, 100, '../assets/cherryjam.webp', 'sauces'),
    ('raspberry_jam', 95.40, 100, '../assets/raspberryjam.webp', 'sauces'),
    ('strawberry_jam', 50.50, 100, '../assets/strawberryjam.jpg', 'sauces'),
    ('pepper_pickle', 40.99, 100, '../assets/pepperpickle.jpg', 'sauces'),
    ('mustard_sauce', 45.80, 100, '../assets/mustardsauce.jpg', 'sauces'),
    ('mixed_pickles', 42.10, 100, '../assets/mixedpickles.jpg', 'sauces'),
    ('mayonnaise', 28.50, 100, '../assets/mayonnaise.jpg', 'sauces'),
    ('ketchup', 35.00, 100, '../assets/ketchup.jpg', 'sauces'),
    ('fig_jam', 43.00, 100, '../assets/figjam.webp', 'sauces'),
    ('cucumber_pickle', 48.00, 100, '../assets/cucumberpickle.jpg', 'sauces'),
    ('corn_pickle', 50.50, 100, '../assets/cornpickle.jpg', 'sauces'),
    ('carrot_pickle', 48.75, 100, '../assets/carrotpickle.jpg', 'sauces'),
    ('cabbage_pickle', 65.30, 100, '../assets/cabbagepickle.jpg', 'sauces'),
    ('barbecue_sauce', 70.25, 100, '../assets/barbecuesauce.jpg', 'sauces'),
    ('apricot_jam', 72.40, 100, '../assets/apricotjam.webp', 'sauces'),
    ('kimchi', 32.80, 100, '../assets/kimchi.jpg', 'sauces');

INSERT INTO product_translations (product_key, language, translated_name) VALUES
                                                                              ('avocado', 'en', 'Avocado'), ('avocado', 'tr', 'Avokado'),
                                                                              ('arugula', 'en', 'Arugula'), ('arugula', 'tr', 'Roka'),
                                                                              ('tomatoes', 'en', 'Tomatoes'), ('tomatoes', 'tr', 'Domates'),
                                                                              ('cucumber', 'en', 'Cucumber'), ('cucumber', 'tr', 'Salatalık'),
                                                                              ('potatoes', 'en', 'Potatoes'), ('potatoes', 'tr', 'Patates'),
                                                                              ('onion', 'en', 'Onion'), ('onion', 'tr', 'Soğan'),
                                                                              ('carrot', 'en', 'Carrot'), ('carrot', 'tr', 'Havuç'),
                                                                              ('zucchini', 'en', 'Zucchini'), ('zucchini', 'tr', 'Kabak'),
                                                                              ('pumpkin', 'en', 'Pumpkin'), ('pumpkin', 'tr', 'Balkabağı'),
                                                                              ('bell_pepper', 'en', 'Bell Pepper'), ('bell_pepper', 'tr', 'Dolmalık Biber'),
                                                                              ('broccoli', 'en', 'Broccoli'), ('broccoli', 'tr', 'Brokoli'),
                                                                              ('capia_pepper', 'en', 'Capia Pepper'), ('capia_pepper', 'tr', 'Kapya Biber'),
                                                                              ('pepper', 'en', 'Pepper'), ('pepper', 'tr', 'Biber'),
                                                                              ('green_pepper', 'en', 'Green Pepper'), ('green_pepper', 'tr', 'Yeşil Biber'),
                                                                              ('sweet_pepper', 'en', 'Sweet Pepper'), ('sweet_pepper', 'tr', 'Tatlı Biber'),
                                                                              ('cherry_tomato', 'en', 'Cherry Tomato'), ('cherry_tomato', 'tr', 'Çeri Domates'),
                                                                              ('celery', 'en', 'Celery'), ('celery', 'tr', 'Kereviz'),
                                                                              ('cauliflower', 'en', 'Cauliflower'), ('cauliflower', 'tr', 'Karnabahar'),
                                                                              ('iceberg_lettuce', 'en', 'Iceberg Lettuce'), ('iceberg_lettuce', 'tr', 'Iceberg Marul'),
                                                                              ('curly_lettuce', 'en', 'Curly Lettuce'), ('curly_lettuce', 'tr', 'Kıvırcık Marul'),
                                                                              ('mushroom', 'en', 'Mushroom'), ('mushroom', 'tr', 'Mantar'),
                                                                              ('garlic', 'en', 'Garlic'), ('garlic', 'tr', 'Sarımsak'),
                                                                              ('red_onion', 'en', 'Red Onion'), ('red_onion', 'tr', 'Kırmızı Soğan'),
                                                                              ('red_pepper', 'en', 'Red Pepper'), ('red_pepper', 'tr', 'Kırmızı Biber'),
                                                                              ('eggplant', 'en', 'Eggplant'), ('eggplant', 'tr', 'Patlıcan'),
                                                                              ('fresh_mint', 'en', 'Fresh Mint'), ('fresh_mint', 'tr', 'Taze Nane'),
                                                                              ('green_bean', 'en', 'Green Bean'), ('green_bean', 'tr', 'Yeşil Fasulye'),
                                                                              ('kale', 'en', 'Kale'), ('kale', 'tr', 'Kale'),
                                                                              ('parsley', 'en', 'Parsley'), ('parsley', 'tr', 'Maydanoz'),
                                                                              ('radish', 'en', 'Radish'), ('radish', 'tr', 'Turp'),
                                                                              ('red_cabbage', 'en', 'Red Cabbage'), ('red_cabbage', 'tr', 'Kırmızı Lahana'),
                                                                              ('scallion', 'en', 'Scallion'), ('scallion', 'tr', 'Taze Soğan'),
                                                                              ('olive_oil_1l', 'en', 'Olive Oil 1L'), ('olive_oil_1l', 'tr', 'Zeytinyağı 1L'),
                                                                              ('olive_oil_tin_5l', 'en', 'Olive Oil Tin 5L'), ('olive_oil_tin_5l', 'tr', 'Zeytinyağı Teneke 5L'),
                                                                              ('sunflower_oil_1l', 'en', 'Sunflower Oil 1L'), ('sunflower_oil_1l', 'tr', 'Ayçiçek Yağı 1L'),
                                                                              ('butter_1kg', 'en', 'Butter 1Kg'), ('butter_1kg', 'tr', 'Tereyağı 1Kg'),
                                                                              ('milk_1l', 'en', 'Milk 1L'), ('milk_1l', 'tr', 'Süt 1L'),
                                                                              ('kefir_1l', 'en', 'Kefir 1L'), ('kefir_1l', 'tr', 'Kefir 1L'),
                                                                              ('cow_feta_cheese', 'en', 'Cow Feta Cheese'), ('cow_feta_cheese', 'tr', 'İnek Beyaz Peynir'),
                                                                              ('twist_cheese', 'en', 'Twist Cheese'), ('twist_cheese', 'tr', 'Örgü Peynir'),
                                                                              ('tulum_cheese', 'en', 'Tulum Cheese'), ('tulum_cheese', 'tr', 'Tulum Peyniri'),
                                                                              ('goat_cheese', 'en', 'Goat Cheese'), ('goat_cheese', 'tr', 'Keçi Peyniri'),
                                                                              ('trakya_aged_cheese', 'en', 'Trakya Aged Cheese'), ('trakya_aged_cheese', 'tr', 'Trakya Eski Peynir'),
                                                                              ('walnut_gouda_cheese', 'en', 'Walnut Gouda Cheese'), ('walnut_gouda_cheese', 'tr', 'Cevizli Gouda Peyniri'),
                                                                              ('gouda_cheese_truffle', 'en', 'Gouda Cheese with Truffle'), ('gouda_cheese_truffle', 'tr', 'Trüf Mantarlı Gouda'),
                                                                              ('gouda_cheese_pesto', 'en', 'Gouda Cheese with Pesto'), ('gouda_cheese_pesto', 'tr', 'Pesto Soslu Gouda'),
                                                                              ('delicious_cheese_balls', 'en', 'Delicious Cheese Balls'), ('delicious_cheese_balls', 'tr', 'Lezzetli Peynir Topları'),
                                                                              ('sheep_yogurt', 'en', 'Sheep Yogurt'), ('sheep_yogurt', 'tr', 'Koyun Yoğurdu'),
                                                                              ('water_buffalo_yogurt', 'en', 'Water Buffalo Yogurt'), ('water_buffalo_yogurt', 'tr', 'Manda Yoğurdu'),
                                                                              ('goat_yogurt', 'en', 'Goat Yogurt'), ('goat_yogurt', 'tr', 'Keçi Yoğurdu'),
                                                                              ('cow_yogurt', 'en', 'Cow Yogurt'), ('cow_yogurt', 'tr', 'İnek Yoğurdu'),
                                                                              ('kars_gruyere_cheese', 'en', 'Kars Gruyere Cheese'), ('kars_gruyere_cheese', 'tr', 'Kars Gravyer Peyniri'),
                                                                              ('string_cheese', 'en', 'String Cheese'), ('string_cheese', 'tr', 'Çeçil Peynir'),
                                                                              ('plaited_cheese', 'en', 'Plaited Cheese'), ('plaited_cheese', 'tr', 'Örgü Peynir'),
                                                                              ('mihali_cheese', 'en', 'Mihali Cheese'), ('mihali_cheese', 'tr', 'Mihaliç Peyniri'),
                                                                              ('kashar_cheese', 'en', 'Kashar Cheese'), ('kashar_cheese', 'tr', 'Kaşar Peynir'),
                                                                              ('herby_cheese', 'en', 'Herby Cheese'), ('herby_cheese', 'tr', 'Otlu Peynir'),
                                                                              ('orange', 'en', 'Orange'), ('orange', 'tr', 'Portakal'),
                                                                              ('banana', 'en', 'Banana'), ('banana', 'tr', 'Muz'),
                                                                              ('grapes', 'en', 'Grapes'), ('grapes', 'tr', 'Üzüm'),
                                                                              ('green_apple', 'en', 'Green Apple'), ('green_apple', 'tr', 'Yeşil Elma'),
                                                                              ('red_apple', 'en', 'Red Apple'), ('red_apple', 'tr', 'Kırmızı Elma'),
                                                                              ('lemon', 'en', 'Lemon'), ('lemon', 'tr', 'Limon'),
                                                                              ('pear', 'en', 'Pear'), ('pear', 'tr', 'Armut'),
                                                                              ('damson', 'en', 'Damson'), ('damson', 'tr', 'Mürdüm Eriği'),
                                                                              ('strawberry', 'en', 'Strawberry'), ('strawberry', 'tr', 'Çilek'),
                                                                              ('green_plum', 'en', 'Green Plum'), ('green_plum', 'tr', 'Erik'),
                                                                              ('watermelon', 'en', 'Watermelon'), ('watermelon', 'tr', 'Karpuz'),
                                                                              ('melon', 'en', 'Melon'), ('melon', 'tr', 'Kavun'),
                                                                              ('pineapple', 'en', 'Pineapple'), ('pineapple', 'tr', 'Ananas'),
                                                                              ('kiwi', 'en', 'Kiwi'), ('kiwi', 'tr', 'Kivi'),
                                                                              ('peach', 'en', 'Peach'), ('peach', 'tr', 'Şeftali'),
                                                                              ('cherry', 'en', 'Cherry'), ('cherry', 'tr', 'Kiraz'),
                                                                              ('pomegranate', 'en', 'Pomegranate'), ('pomegranate', 'tr', 'Nar'),
                                                                              ('purple_fig', 'en', 'Purple Fig'), ('purple_fig', 'tr', 'Mor İncir'),
                                                                              ('green_fig', 'en', 'Green Fig'), ('green_fig', 'tr', 'Yeşil İncir'),
                                                                              ('quince', 'en', 'Quince'), ('quince', 'tr', 'Ayva'),
                                                                              ('dragon_fruit', 'en', 'Dragon Fruit'), ('dragon_fruit', 'tr', 'Pitaya'),
                                                                              ('bread', 'en', 'Bread'), ('bread', 'tr', 'Ekmek'),
                                                                              ('daisy_bread', 'en', 'Daisy Bread'), ('daisy_bread', 'tr', 'Papatya Ekmek'),
                                                                              ('corn_bread', 'en', 'Corn Bread'), ('corn_bread', 'tr', 'Mısır Ekmeği'),
                                                                              ('pitta_bread', 'en', 'Pitta Bread'), ('pitta_bread', 'tr', 'Pide Ekmeği'),
                                                                              ('sourdough_bread', 'en', 'Sourdough Bread'), ('sourdough_bread', 'tr', 'Ekşi Maya Ekmek'),
                                                                              ('brown_bread', 'en', 'Brown Bread'), ('brown_bread', 'tr', 'Kepekli Ekmek'),
                                                                              ('multigrain_bread', 'en', 'Multigrain Bread'), ('multigrain_bread', 'tr', 'Çok Tahıllı Ekmek'),
                                                                              ('village_bread', 'en', 'Village Bread'), ('village_bread', 'tr', 'Köy Ekmeği'),
                                                                              ('whole_wheat_bread', 'en', 'Whole Wheat Bread'), ('whole_wheat_bread', 'tr', 'Tam Buğday Ekmeği'),
                                                                              ('bagel', 'en', 'Bagel'), ('bagel', 'tr', 'Simit'),
                                                                              ('gevrek', 'en', 'Gevrek'), ('gevrek', 'tr', 'Gevrek'),
                                                                              ('croissant', 'en', 'Croissant'), ('croissant', 'tr', 'Kruvasan'),
                                                                              ('pastry', 'en', 'Pastry'), ('pastry', 'tr', 'Poğaça'),
                                                                              ('pastry_cheese', 'en', 'Cheese Pastry'), ('pastry_cheese', 'tr', 'Peynirli Poğaça'),
                                                                              ('pastry_olive', 'en', 'Olive Pastry'), ('pastry_olive', 'tr', 'Zeytinli Poğaça'),
                                                                              ('spring_rolls', 'en', 'Spring Rolls'), ('spring_rolls', 'tr', 'Sigara Böreği'),
                                                                              ('cake', 'en', 'Cake'), ('cake', 'tr', 'Kek'),
                                                                              ('chocolate_cake', 'en', 'Chocolate Cake'), ('chocolate_cake', 'tr', 'Çikolatalı Kek'),
                                                                              ('blackberry_jam', 'en', 'Blackberry Jam'), ('blackberry_jam', 'tr', 'Böğürtlen Reçeli'),
                                                                              ('cherry_jam', 'en', 'Cherry Jam'), ('cherry_jam', 'tr', 'Vişne Reçeli'),
                                                                              ('raspberry_jam', 'en', 'Raspberry Jam'), ('raspberry_jam', 'tr', 'Ahududu Reçeli'),
                                                                              ('strawberry_jam', 'en', 'Strawberry Jam'), ('strawberry_jam', 'tr', 'Çilek Reçeli'),
                                                                              ('pepper_pickle', 'en', 'Pepper Pickle'), ('pepper_pickle', 'tr', 'Biber Turşusu'),
                                                                              ('mustard_sauce', 'en', 'Mustard Sauce'), ('mustard_sauce', 'tr', 'Hardal Sosu'),
                                                                              ('mixed_pickles', 'en', 'Mixed Pickles'), ('mixed_pickles', 'tr', 'Karışık Turşu'),
                                                                              ('mayonnaise', 'en', 'Mayonnaise'), ('mayonnaise', 'tr', 'Mayonez'),
                                                                              ('ketchup', 'en', 'Ketchup'), ('ketchup', 'tr', 'Ketçap'),
                                                                              ('fig_jam', 'en', 'Fig Jam'), ('fig_jam', 'tr', 'İncir Reçeli'),
                                                                              ('cucumber_pickle', 'en', 'Cucumber Pickle'), ('cucumber_pickle', 'tr', 'Salatalık Turşusu'),
                                                                              ('corn_pickle', 'en', 'Corn Pickle'), ('corn_pickle', 'tr', 'Mısır Turşusu'),
                                                                              ('carrot_pickle', 'en', 'Carrot Pickle'), ('carrot_pickle', 'tr', 'Havuç Turşusu'),
                                                                              ('cabbage_pickle', 'en', 'Cabbage Pickle'), ('cabbage_pickle', 'tr', 'Lahana Turşusu'),
                                                                              ('barbecue_sauce', 'en', 'Barbecue Sauce'), ('barbecue_sauce', 'tr', 'Barbekü Sos'),
                                                                              ('apricot_jam', 'en', 'Apricot Jam'), ('apricot_jam', 'tr', 'Kayısı Reçeli'),
                                                                              ('kimchi', 'en', 'Kimchi'), ('kimchi', 'tr', 'Kimçi');